### ISSUE TITLE
No padding on alert class

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1525]
### Expected behavior

Padding on alert class between icon and text.

### Actual behavior

No padding, making the text looked cramped.

### Steps to reproduce the behavior

1. Visit https://elementary.io/404
2. ???
3. Profit

### Image

![screenshot from 2017-01-02 17 30 50](https://cloud.githubusercontent.com/assets/3385679/21598002/59c5d14e-d111-11e6-85aa-9864fb08f881.png)

**Comment by zhenghao1** [comment]
How about some padding and margin?  Something like 5px for each?

```css
.column.alert {
  max-width: calc(100% - 70px) /* Already there */
  padding: 5px;
  margin: 5px;
}
```

**Comment by btkostner** [comment]
Looks good to me. Don't forget to sort the lines though so it goes:
```css
.column.alert {
  margin: 5px;
  max-width: calc(100% - 70px);
  padding: 5px;
}
```
