### ISSUE TITLE
Change the bg color

### ISSUE THREAD

**Issue by rajatgupta24** [elementary/website#2950]
### Problem

background of privacy section in landing page
![image](https://user-images.githubusercontent.com/55191777/151654858-4a549b4c-a39b-47a4-8406-4493cd50b7d3.png)

### Proposal

Change the background to a black gradient shade, looks a little more clean
![image](https://user-images.githubusercontent.com/55191777/151654905-5e6295f9-6d8f-46c0-a9d2-862ff06381f3.png)

**Comment by sahithyandev** [comment]
```css
#privacy {
  /* background-color: #273445; */
  background-image: radial-gradient(ellipse at center, #262525 4%, black);
}
```

This is the only change required to achieve the design suggested above.
